### ISSUE TITLE
Missing dark current file?

### ISSUE THREAD

**Issue by serbinsh** [amcmahonBNL/UnispecProcessing#14]
@amcmahon01 Based on this: https://github.com/TESTgroup-BNL/UniSpec_Processing/blob/6ababd51824653a87af5d1c91aa9e31ddf7c5a4e/src/config.txt#L7

It looks like the Dark10.spu file is missing from the src directory....should we include it there or in another  "inputs" or similar directory where we could add different inputs?

**Comment by amcmahon01** [comment]
Unless we think the same file can be used "permanently", I think eventually they should have their own directory.  But they were supposed to be in src for now (now added).
